#!/usr/bin/env node
/**
 * Build the icon sprite + types from <repo-root>/svg/*.svg.
 *
 * Outputs (relative to packages/ui):
 *   src/icons/sprite.gen.tsx  — <IconSprite /> React component (mount once at app root)
 *   src/icons/icons.gen.ts    — IconName union + ICON_NAMES const array
 *
 * Source SVGs at <repo-root>/svg/ are normalized:
 *   - fill="black"|"#000"|"#000000"  → fill="currentColor"
 *   - stroke="black"|"#000"|"#000000" → stroke="currentColor"
 *   - internal id="X" / url(#X) / href="#X" prefixed with `<icon-id>__` to prevent
 *     collisions across symbols in the same sprite
 *
 * Run via:  node scripts/build-icons.mjs   (from packages/ui/)
 */
import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { join, basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
// packages/ui/scripts → repo root = ../../..
const REPO_ROOT = join(HERE, "..", "..", "..");
const SVG_DIR = join(REPO_ROOT, "svg");
const OUT_DIR = join(HERE, "..", "src", "icon-system");

if (!existsSync(SVG_DIR)) {
  console.error(`[build-icons] svg source not found: ${SVG_DIR}`);
  process.exit(1);
}
if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true });

const files = readdirSync(SVG_DIR)
  .filter((f) => f.toLowerCase().endsWith(".svg"))
  .sort();

if (files.length === 0) {
  console.error(`[build-icons] no .svg files in ${SVG_DIR}`);
  process.exit(1);
}

const symbols = [];
const names = [];
const idCollisions = new Map();

for (const file of files) {
  const id = slugify(basename(file, ".svg"));
  if (idCollisions.has(id)) {
    console.error(
      `[build-icons] icon id collision: "${id}" from ${file} and ${idCollisions.get(id)}`,
    );
    process.exit(1);
  }
  idCollisions.set(id, file);

  const raw = readFileSync(join(SVG_DIR, file), "utf8");
  symbols.push(svgToSymbol(raw, id, file));
  names.push(id);
}

const spriteHtml = symbols.join("");
const spriteFile = `// AUTO-GENERATED by scripts/build-icons.mjs — DO NOT EDIT.
// Regenerate with: npm run build:icons (from packages/ui)
import * as React from "react";

const SPRITE_HTML = ${JSON.stringify(spriteHtml)};

/**
 * Mount once at the app root (e.g. inside <body> in Next.js layout).
 * All <Icon> instances reference symbols inside this hidden sprite via <use href="#id">.
 */
export function IconSprite() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      style={{ position: "absolute", width: 0, height: 0, overflow: "hidden" }}
      aria-hidden="true"
      data-icon-sprite
      dangerouslySetInnerHTML={{ __html: SPRITE_HTML }}
    />
  );
}
`;
writeFileSync(join(OUT_DIR, "sprite.gen.tsx"), spriteFile);

const typesFile = `// AUTO-GENERATED by scripts/build-icons.mjs — DO NOT EDIT.
// Regenerate with: npm run build:icons (from packages/ui)

export const ICON_NAMES = [
${names.map((n) => `  "${n}",`).join("\n")}
] as const;

export type IconName = (typeof ICON_NAMES)[number];
`;
writeFileSync(join(OUT_DIR, "icons.gen.ts"), typesFile);

console.log(`[build-icons] ${names.length} icons → ${OUT_DIR}`);

// ──────────────────────────────────────────────────────────────────────────
// helpers
// ──────────────────────────────────────────────────────────────────────────

function slugify(name) {
  return name
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function svgToSymbol(raw, id, sourceFile) {
  const viewBoxMatch = raw.match(/viewBox="([^"]+)"/);
  if (!viewBoxMatch) {
    throw new Error(`[build-icons] ${sourceFile}: missing viewBox`);
  }
  const viewBox = viewBoxMatch[1];

  // 루트 <svg>의 fill 속성 보존. <symbol>로 옮기면서 root attrs가 떨어지면
  // stroke-only 아이콘(원본이 fill="none")이 SVG 기본 fill="black"을 갖게 돼서
  // currentColor stroke만 의도해도 검은 채움이 남는다.
  const rootMatch = raw.match(/<svg([^>]*)>/i);
  const rootAttrs = rootMatch ? rootMatch[1] : '';
  const rootFillMatch = rootAttrs.match(/\sfill="([^"]+)"/i);
  const rootFill = rootFillMatch ? rootFillMatch[1] : null;

  const innerMatch = raw.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
  if (!innerMatch) {
    throw new Error(`[build-icons] ${sourceFile}: could not extract inner SVG`);
  }
  let inner = innerMatch[1].trim();

  // 모든 fill/stroke/stop-color를 currentColor로 정규화한다 — color prop으로
  // 모든 hex 톤을 덮을 수 있어야 한다.
  // 예외:
  //   - 'none' : 명시적 비활성. 그대로 둠 (root fill="none" stroke-only 아이콘 포함).
  //   - 'url(#...)' : gradient/pattern 참조. currentColor로 못 바꿈.
  //   - <clipPath>, <mask> 블록 내부의 모든 색: 마스킹 영역 정의용. 회색으로 바뀌면
  //     마스크가 깨지므로 정규화 대상에서 블록째 제외한다.
  const blocks = [];
  inner = inner.replace(/<(clipPath|mask)[^>]*>[\s\S]*?<\/\1>/gi, (m) => {
    const i = blocks.length;
    blocks.push(m);
    return `__BUILD_ICONS_PRESERVE_${i}__`;
  });

  const PRESERVE = /^(none|url\(.*\))$/i;
  for (const attr of ["fill", "stroke", "stop-color"]) {
    inner = inner.replace(
      new RegExp(`${attr}="([^"]+)"`, "gi"),
      (m, value) => (PRESERVE.test(value) ? m : `${attr}="currentColor"`),
    );
  }

  inner = inner.replace(
    /__BUILD_ICONS_PRESERVE_(\d+)__/g,
    (_, i) => blocks[+i],
  );

  // Gradient collapse: 모든 stop이 currentColor가 된 linear/radialGradient는
  // 단색이 된 것과 다를 바 없는데, <use> shadow tree 안에서는 stop-color의
  // currentColor inheritance가 SVG 사양상 불안정해서 일부 브라우저가 검정으로
  // 폴백한다. gradient 참조 자체를 currentColor로 치환하고 defs는 그대로 둔다
  // (사용처가 없어진 dead code).
  const gradients = [
    ...inner.matchAll(
      /<(linearGradient|radialGradient)\s[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/\1>/gi,
    ),
  ];
  for (const [, , gradId, body] of gradients) {
    const stops = [...body.matchAll(/stop-color="([^"]+)"/gi)];
    if (stops.length === 0) continue;
    if (stops.every(([, c]) => c.toLowerCase() === "currentcolor")) {
      const urlRef = `url(#${gradId})`;
      inner = inner.split(`fill="${urlRef}"`).join('fill="currentColor"');
      inner = inner.split(`stroke="${urlRef}"`).join('stroke="currentColor"');
    }
  }

  // Prefix all internal IDs to avoid cross-symbol collisions when sprite is mounted.
  const internalIds = [...inner.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1]);
  for (const internalId of internalIds) {
    const safe = `${id}__${internalId}`;
    inner = inner.split(`id="${internalId}"`).join(`id="${safe}"`);
    inner = inner.split(`url(#${internalId})`).join(`url(#${safe})`);
    inner = inner.split(`href="#${internalId}"`).join(`href="#${safe}"`);
    inner = inner.split(`xlink:href="#${internalId}"`).join(`xlink:href="#${safe}"`);
  }

  const fillAttr = rootFill ? ` fill="${rootFill}"` : "";
  return `<symbol id="${id}" viewBox="${viewBox}"${fillAttr}>${inner}</symbol>`;
}
