// AUTO-GENERATED by scripts/build-icons.mjs — DO NOT EDIT.
// Regenerate with: npm run build:icons (from packages/ui)

export const ICON_NAMES = [
  "ic-iaan-crime-type",
  "ic-iaan-data-request",
  "ic-iaan-freeze-request",
  "ic-iaan-info-request",
  "ic-iaan-open-management",
  "ic-map-autotrace",
  "ic-map-cluster",
  "ic-map-crypto",
  "ic-map-dollar",
  "ic-map-won",
  "ic-menu-analytics",
  "ic-menu-dashboard",
  "ic-menu-data-request",
  "ic-menu-monitoring",
  "ic-menu-txmap",
  "ic-search-chain-type",
  "ic-trace-bridge",
  "ic-trace-ca",
  "ic-trace-canvas",
  "ic-trace-dt",
  "ic-trace-search-history",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
